In [3]:
import pandas as pd
import numpy as np

In [10]:
df_customers=pd.read_csv("/content/AWCustomers.csv.zip")
df_sales=pd.read_csv("/content/AWSales.csv")

In [11]:
df_customers.head()

,CustomerID,Title,FirstName,MiddleName,LastName,Suffix,AddressLine1,AddressLine2,City,StateProvinceName,...,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,LastUpdated
0,21173,NaN,Chad,C,Yuan,NaN,7090 C. Mount Hood,NaN,Wollongong,New South Wales,...,Bachelors,Clerical,M,M,1,3,0,1,81916,2017-03-06
1,13249,NaN,Ryan,NaN,Perry,NaN,3651 Willow Lake Rd,NaN,Shawnee,British Columbia,...,Partial College,Clerical,M,M,1,2,1,2,81076,2017-03-06
2,29350,NaN,Julia,NaN,Thompson,NaN,1774 Tice Valley Blvd.,NaN,West Covina,California,...,Bachelors,Clerical,F,S,0,3,0,0,86387,2017-03-06
3,13503,NaN,Theodore,NaN,Gomez,NaN,2103 Baldwin Dr,NaN,Liverpool,England,...,Partial College,Skilled Manual,M,M,1,2,1,2,61481,2017-03-06
4,22803,NaN,Marshall,J,Shan,NaN,Am Gallberg 234,NaN,Werne,Nordrhein-Westfalen,...,Partial College,Skilled Manual,M,S,1,1,0,0,51804,2017-03-06

In [ ]:
df_sales.head()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [12]:
df_customers.shape

(18361, 24)

In [13]:
df_customers.CustomerID.nunique() #checking unique values in customer id attribute

18355

In [14]:
df_customers.Title.isnull().sum() #checking null values in title attribute

18260

In [15]:
df_customers.Suffix.isnull().sum() #checking null values in title attribute

18358

In [16]:
df_customers.LastUpdated.nunique() #checking unique values in lastupdate attribute

2

In [17]:
df_customers.columns #Checking the names of each column

Index(['CustomerID', 'Title', 'FirstName', 'MiddleName', 'LastName', 'Suffix',
       'AddressLine1', 'AddressLine2', 'City', 'StateProvinceName',
       'CountryRegionName', 'PostalCode', 'PhoneNumber', 'BirthDate',
       'Education', 'Occupation', 'Gender', 'MaritalStatus', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'LastUpdated'],
      dtype='object')

In [18]:
x = ['CustomerID','Title','MiddleName','Suffix','AddressLine2','PostalCode','AddressLine1','City','PhoneNumber','FirstName','LastName','LastUpdated']
df1 = df_customers.drop(x,axis = 1) # loading the data into df2 after dropping all the attributes

In [19]:
df1.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076
2,California,United States,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804

In [20]:
df_customers.NumberCarsOwned.unique() # checking null values of numbercarsowned attribute

array([3, 2, 1, 0, 4, 5])

In [21]:
df_customers.HomeOwnerFlag.unique()

array([1, 0])

In [22]:
df_customers.Occupation.unique()

array(['Clerical', 'Skilled Manual', 'Manual', 'Management',
       'Professional'], dtype=object)

In [23]:
df1.drop_duplicates() # removing the redundant data

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076
2,California,United States,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804
...,...,...,...,...,...,...,...,...,...,...,...,...
18356,California,United States,1990-11-11,Graduate Degree,Skilled Manual,F,M,0,1,0,2,52953
18357,New South Wales,Australia,1992-10-13,Bachelors,Skilled Manual,F,S,0,2,0,0,60992
18358,Oregon,United States,1983-11-24,Partial College,Skilled Manual,F,S,0,2,0,0,51859
18359,British Columbia,Canada,1995-06-15,High School,Clerical,F,S,0,0,0,0,87177
18360,California,United States,1986-03-26,Graduate Degree,Professional,F,M,1,2,0,0,136856

In [24]:
df1.shape # after removing redundant data

(18361, 12)

In [25]:
df1.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076
2,California,United States,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804

In [26]:
df1.isnull().sum()

StateProvinceName       0
CountryRegionName       0
BirthDate               0
Education               0
Occupation              0
Gender                  0
MaritalStatus           0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
dtype: int64

In [28]:
from scipy.stats import zscore

In [29]:
df1['numbercarsowned '] = zscore(df1['NumberCarsOwned'])
df1['NumberChildrenathome'] = zscore(df1['NumberChildrenAtHome'])
df1['totalChildren'] = zscore(df1['TotalChildren'])
df1['yearlyincome '] = zscore(df1['YearlyIncome'])

In [30]:
df1.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,NumberCarsOwned,NumberChildrenAtHome,TotalChildren,YearlyIncome,numbercarsowned,NumberChildrenathome,totalChildren,yearlyincome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,M,M,1,3,0,1,81916,1.892524,-0.594371,0.161342,0.298555
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,M,M,1,2,1,2,81076,0.798389,1.163279,1.239753,0.271180
2,California,United States,1985-11-09,Bachelors,Clerical,F,S,0,3,0,0,86387,1.892524,-0.594371,-0.917069,0.444261
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,M,M,1,2,1,2,61481,0.798389,1.163279,1.239753,-0.367401
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,M,S,1,1,0,0,51804,-0.295746,-0.594371,-0.917069,-0.682765

In [31]:
X = ['NumberCarsOwned','TotalChildren','YearlyIncome','NumberChildrenAtHome']
df2 = df1.drop(X,axis = 1)

In [32]:
df2.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,numbercarsowned,NumberChildrenathome,totalChildren,yearlyincome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,M,M,1,1.892524,-0.594371,0.161342,0.298555
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,M,M,1,0.798389,1.163279,1.239753,0.271180
2,California,United States,1985-11-09,Bachelors,Clerical,F,S,0,1.892524,-0.594371,-0.917069,0.444261
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,M,M,1,0.798389,1.163279,1.239753,-0.367401
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,M,S,1,-0.295746,-0.594371,-0.917069,-0.682765

In [33]:
df2['Gender'] = df2['Gender'].apply(lambda x : 0 if x == 'M' else 1)
df2['MaritalStatus'] = df2['MaritalStatus'].apply(lambda x : 0 if x == 'M' else 1)

In [34]:
df2.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,numbercarsowned,NumberChildrenathome,totalChildren,yearlyincome
0,New South Wales,Australia,1987-11-13,Bachelors,Clerical,0,0,1,1.892524,-0.594371,0.161342,0.298555
1,British Columbia,Canada,1972-07-21,Partial College,Clerical,0,0,1,0.798389,1.163279,1.239753,0.271180
2,California,United States,1985-11-09,Bachelors,Clerical,1,1,0,1.892524,-0.594371,-0.917069,0.444261
3,England,United Kingdom,1977-10-18,Partial College,Skilled Manual,0,0,1,0.798389,1.163279,1.239753,-0.367401
4,Nordrhein-Westfalen,Germany,1975-02-05,Partial College,Skilled Manual,0,1,1,-0.295746,-0.594371,-0.917069,-0.682765

In [35]:
df2.Education.unique()

array(['Bachelors', 'Partial College', 'High School',
       'Partial High School', 'Graduate Degree'], dtype=object)

In [36]:
def edu(x):
    if x=='Bachelors':
        x= 3
    elif x == 'Graduate Degree':
        x = 3
    elif x=='Partial College':
        x= 2
    elif x=='High School':
        x= 1
    else:
        x= 0
    return x

In [37]:
df2['Education'] = df2['Education'].apply(edu)

In [38]:
df2.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,numbercarsowned,NumberChildrenathome,totalChildren,yearlyincome
0,New South Wales,Australia,1987-11-13,3,Clerical,0,0,1,1.892524,-0.594371,0.161342,0.298555
1,British Columbia,Canada,1972-07-21,2,Clerical,0,0,1,0.798389,1.163279,1.239753,0.271180
2,California,United States,1985-11-09,3,Clerical,1,1,0,1.892524,-0.594371,-0.917069,0.444261
3,England,United Kingdom,1977-10-18,2,Skilled Manual,0,0,1,0.798389,1.163279,1.239753,-0.367401
4,Nordrhein-Westfalen,Germany,1975-02-05,2,Skilled Manual,0,1,1,-0.295746,-0.594371,-0.917069,-0.682765

In [39]:
dummies = pd.get_dummies(df2.Occupation)
dummies1 = pd.get_dummies(df2.CountryRegionName)
dummies2 = pd.get_dummies(df2.StateProvinceName)

In [40]:
dummies

       Clerical  Management  Manual  Professional  Skilled Manual
0          True       False   False         False           False
1          True       False   False         False           False
2          True       False   False         False           False
3         False       False   False         False            True
4         False       False   False         False            True
...         ...         ...     ...           ...             ...
18356     False       False   False         False            True
18357     False       False   False         False            True
18358     False       False   False         False            True
18359      True       False   False         False           False
18360     False       False   False          True           False

[18361 rows x 5 columns]

In [41]:
dummies1

       Australia  Canada  France  Germany  United Kingdom  United States
0           True   False   False    False           False          False
1          False    True   False    False           False          False
2          False   False   False    False           False           True
3          False   False   False    False            True          False
4          False   False   False     True           False          False
...          ...     ...     ...      ...             ...            ...
18356      False   False   False    False           False           True
18357       True   False   False    False           False          False
18358      False   False   False    False           False           True
18359      False    True   False    False           False          False
18360      False   False   False    False           False           True

[18361 rows x 6 columns]

In [42]:
dummies2

,Alabama,Alberta,Arizona,Bayern,Brandenburg,British Columbia,California,Charente-Maritime,England,Essonne,...,Tasmania,Texas,Utah,Val d'Oise,Val de Marne,Victoria,Virginia,Washington,Wyoming,Yveline
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18356,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18357,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18358,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18359,False,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
18360,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [43]:
df3 = pd.concat([df2,dummies.drop('Skilled Manual',axis='columns'),dummies1.drop('United States',axis='columns'),dummies2.drop('Yveline',axis='columns')],axis='columns')
df3.head()

,StateProvinceName,CountryRegionName,BirthDate,Education,Occupation,Gender,MaritalStatus,HomeOwnerFlag,numbercarsowned,NumberChildrenathome,...,South Carolina,Tasmania,Texas,Utah,Val d'Oise,Val de Marne,Victoria,Virginia,Washington,Wyoming
0,New South Wales,Australia,1987-11-13,3,Clerical,0,0,1,1.892524,-0.594371,...,False,False,False,False,False,False,False,False,False,False
1,British Columbia,Canada,1972-07-21,2,Clerical,0,0,1,0.798389,1.163279,...,False,False,False,False,False,False,False,False,False,False
2,California,United States,1985-11-09,3,Clerical,1,1,0,1.892524,-0.594371,...,False,False,False,False,False,False,False,False,False,False
3,England,United Kingdom,1977-10-18,2,Skilled Manual,0,0,1,0.798389,1.163279,...,False,False,False,False,False,False,False,False,False,False
4,Nordrhein-Westfalen,Germany,1975-02-05,2,Skilled Manual,0,1,1,-0.295746,-0.594371,...,False,False,False,False,False,False,False,False,False,False

In [44]:
df4 = df3.drop(['StateProvinceName','CountryRegionName','Occupation'],axis = 1)

In [45]:
df4.head()

,BirthDate,Education,Gender,MaritalStatus,HomeOwnerFlag,numbercarsowned,NumberChildrenathome,totalChildren,yearlyincome,Clerical,...,South Carolina,Tasmania,Texas,Utah,Val d'Oise,Val de Marne,Victoria,Virginia,Washington,Wyoming
0,1987-11-13,3,0,0,1,1.892524,-0.594371,0.161342,0.298555,True,...,False,False,False,False,False,False,False,False,False,False
1,1972-07-21,2,0,0,1,0.798389,1.163279,1.239753,0.271180,True,...,False,False,False,False,False,False,False,False,False,False
2,1985-11-09,3,1,1,0,1.892524,-0.594371,-0.917069,0.444261,True,...,False,False,False,False,False,False,False,False,False,False
3,1977-10-18,2,0,0,1,0.798389,1.163279,1.239753,-0.367401,False,...,False,False,False,False,False,False,False,False,False,False
4,1975-02-05,2,0,1,1,-0.295746,-0.594371,-0.917069,-0.682765,False,...,False,False,False,False,False,False,False,False,False,False

In [1]:
from sklearn.metrics import jaccard_score

In [ ]:
correlations = df4.corr(method = 'pearson')

In [3]:
correlations